version: '3.9'

services:
  coredns:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coredns
    restart: always
    expose:
      - '53'
      - '53/udp'
    ports:
      - '127.0.0.1:53:53'
      - '127.0.0.1:53:53/udp'
